export interface Ability {
  name: string
  sequence: string
  image: ImageType
}

export type ImageType = typeof imageNames[number]

const imageNames = [
  'reinforce.svg',
  'resupply.svg',
  'sos_beacon.svg',
  'seaf_artillery.svg',
  'hellbomb.svg',
  'prospecting_drill.svg',
  'super_earth_flag.svg',
  'upload_data.svg',
  'machine_gun.svg',
  'anti-materiel_rifle.svg',
  'stalwart.svg',
  'expendable_anti-tank.svg',
  'recoilless_rifle.svg',
  'flamethrower.svg',
  'autocannon.svg',
  'railgun.svg',
  'spear.svg',
  'orbital_gatling_barrage.svg',
  'orbital_airburst_strike.svg',
  'orbital_120mm_he_barrage.svg',
  'orbital_380mm_he_barrage.svg',
  'orbital_walking_barrage.svg',
  'orbital_laser.svg',
  'orbital_railcannon_strike.svg',
  'eagle_strafing_run.svg',
  'eagle_airstrike.svg',
  'eagle_cluster_bomb.svg',
  'eagle_napalm_airstrike.svg',
  'jump_pack.svg',
  'eagle_smoke_strike.svg',
  'eagle_110mm_rocket_pods.svg',
  'eagle_500kg_bomb.svg',
  'eagle_rearm.svg',
  'orbital_precision_strike.svg',
  'orbital_gas_strike.svg',
  'orbital_ems_strike.svg',
  'orbital_smoke_strike.svg',
  'hmg_emplacement.svg',
  'shield_generator_pack.svg',
  'tesla_tower.svg',
  'anti-personnel_minefield.svg',
  'supply_pack.svg',
  'grenade_launcher.svg',
  'laser_cannon.svg',
  'incendiary_mines.svg',
  'guard_dog_rover.svg',
  'ballistic_shield_backpack.svg',
  'arc_thrower.svg',
  'machine_gun_sentry.svg',
  'gatling_sentry.svg',
  'mortar_sentry.svg',
  'guard_dog.svg',
  'autocannon_sentry.svg',
  'rocket_sentry.svg',
  'ems_mortar_sentry.svg',
  'patriot_exosuit.svg',
] as const
