import type { HD2StratagemsData } from '~/types/common'

const hd2Sequences: HD2StratagemsData[] = [
  {
    id: 0,
    name: 'Reinforce',
    sequence: 'UDRLU',
    image: 'reinforce.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 1,
    name: 'Resupply',
    sequence: 'DDUR',
    image: 'resupply.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 2,
    name: 'SOS Beacon',
    sequence: 'UDRU',
    image: 'sos_beacon.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 3,
    name: 'SEAF Artillery',
    sequence: 'RUUD',
    image: 'seaf_artillery.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 4,
    name: 'Hellbomb',
    sequence: 'DULDURDU',
    image: 'hellbomb.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 5,
    name: 'Prospecting Drill',
    sequence: 'DDLRDD',
    image: 'prospecting_drill.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 6,
    name: 'Super Earth Flag',
    sequence: 'DUDU',
    image: 'super_earth_flag.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 7,
    name: 'Upload Data',
    sequence: 'LRUUU',
    image: 'upload_data.svg',
    groupId: 'general_stratagems',
    group: 'General Stratagems',
  },
  {
    id: 8,
    name: 'Machine Gun',
    sequence: 'DLDUR',
    image: 'machine_gun.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 9,
    name: 'Anti-Materiel Rifle',
    sequence: 'DLRUD',
    image: 'anti-materiel_rifle.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 10,
    name: 'Stalwart',
    sequence: 'DLDUUL',
    image: 'stalwart.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 11,
    name: 'Expendable Anti-Tank',
    sequence: 'DDLUR',
    image: 'expendable_anti-tank.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 12,
    name: 'Recoilless Rifle',
    sequence: 'DLRRL',
    image: 'recoilless_rifle.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 13,
    name: 'Flamethrower',
    sequence: 'DLUDU',
    image: 'flamethrower.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 14,
    name: 'Autocannon',
    sequence: 'DLDUUR',
    image: 'autocannon.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 15,
    name: 'Railgun',
    sequence: 'DRDULR',
    image: 'railgun.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 16,
    name: 'Spear',
    sequence: 'DDUDD',
    image: 'spear.svg',
    groupId: 'patriotic_administration_center',
    group: 'Patriotic Administration Center',
  },
  {
    id: 17,
    name: 'Orbital Gatling Barrage',
    sequence: 'RDLUU',
    image: 'orbital_gatling_barrage.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 18,
    name: 'Orbital Airburst Strike',
    sequence: 'RRR',
    image: 'orbital_airburst_strike.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 19,
    name: 'Orbital 120MM HE Barrage',
    sequence: 'RRDLRD',
    image: 'orbital_120mm_he_barrage.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 20,
    name: 'Orbital 380MM HE Barrage',
    sequence: 'RDUULDD',
    image: 'orbital_380mm_he_barrage.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 21,
    name: 'Orbital Walking Barrage',
    sequence: 'RDRDRD',
    image: 'orbital_walking_barrage.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 22,
    name: 'Orbital Laser',
    sequence: 'RDURD',
    image: 'orbital_laser.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 23,
    name: 'Orbital Railcannon Strike',
    sequence: 'RUDDR',
    image: 'orbital_railcannon_strike.svg',
    groupId: 'orbital_cannons',
    group: 'Orbital Cannons',
  },
  {
    id: 24,
    name: 'Eagle Strafing Run',
    sequence: 'URR',
    image: 'eagle_strafing_run.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 25,
    name: 'Eagle Airstrike',
    sequence: 'URDR',
    image: 'eagle_airstrike.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 26,
    name: 'Eagle Cluster Bomb',
    sequence: 'URDDR',
    image: 'eagle_cluster_bomb.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 27,
    name: 'Eagle Napalm Airstrike',
    sequence: 'URDU',
    image: 'eagle_napalm_airstrike.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 28,
    name: 'Jump Pack',
    sequence: 'DUUDU',
    image: 'jump_pack.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 29,
    name: 'Eagle Smoke Strike',
    sequence: 'URUD',
    image: 'eagle_smoke_strike.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 30,
    name: 'Eagle 110MM Rocket Pods',
    sequence: 'URUL',
    image: 'eagle_110mm_rocket_pods.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 31,
    name: 'Eagle 500KG Bomb',
    sequence: 'URDDD',
    image: 'eagle_500kg_bomb.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 32,
    name: 'Eagle Rearm',
    sequence: 'UULUR',
    image: 'eagle_rearm.svg',
    groupId: 'hangar',
    group: 'Hangar',
  },
  {
    id: 33,
    name: 'Orbital Precision Strike',
    sequence: 'RRU',
    image: 'orbital_precision_strike.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 34,
    name: 'Orbital Gas Strike',
    sequence: 'RRDR',
    image: 'orbital_gas_strike.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 35,
    name: 'Orbital EMS Strike',
    sequence: 'RRLD',
    image: 'orbital_ems_strike.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 36,
    name: 'Orbital Smoke Strike',
    sequence: 'RRDU',
    image: 'orbital_smoke_strike.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 37,
    name: 'HMG Emplacement',
    sequence: 'DULRRL',
    image: 'hmg_emplacement.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 38,
    name: 'Shield Generator Pack',
    sequence: 'DULRLR',
    image: 'shield_generator_pack.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 39,
    name: 'Tesla Tower',
    sequence: 'DURULR',
    image: 'tesla_tower.svg',
    groupId: 'bridge',
    group: 'Bridge',
  },
  {
    id: 40,
    name: 'Anti-Personnel Minefield',
    sequence: 'DLUR',
    image: 'anti-personnel_minefield.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 41,
    name: 'Supply Pack',
    sequence: 'DLDUUD',
    image: 'supply_pack.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 42,
    name: 'Grenade Launcher',
    sequence: 'DLULD',
    image: 'grenade_launcher.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 43,
    name: 'Laser Cannon',
    sequence: 'DLDUL',
    image: 'laser_cannon.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 44,
    name: 'Incendiary Mines',
    sequence: 'DLLD',
    image: 'incendiary_mines.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 45,
    name: 'Guard Dog Rover',
    sequence: 'DULURR',
    image: 'guard_dog_rover.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 46,
    name: 'Ballistic Shield Backpack',
    sequence: 'DLDDUL',
    image: 'ballistic_shield_backpack.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 47,
    name: 'Arc Thrower',
    sequence: 'DRDULL',
    image: 'arc_thrower.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 48,
    name: 'Shield Generator Pack',
    sequence: 'DULRLR',
    image: 'shield_generator_pack.svg',
    groupId: 'engineering_bay',
    group: 'Engineering Bay',
  },
  {
    id: 49,
    name: 'Machine Gun Sentry',
    sequence: 'DURRU',
    image: 'machine_gun_sentry.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 50,
    name: 'Gatling Sentry',
    sequence: 'DURL',
    image: 'gatling_sentry.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 51,
    name: 'Mortar Sentry',
    sequence: 'DURRD',
    image: 'mortar_sentry.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 52,
    name: 'Guard Dog',
    sequence: 'DULURD',
    image: 'guard_dog.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 53,
    name: 'Autocannon Sentry',
    sequence: 'DURULU',
    image: 'autocannon_sentry.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 54,
    name: 'Rocket Sentry',
    sequence: 'DURRL',
    image: 'rocket_sentry.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 55,
    name: 'EMS Mortar Sentry',
    sequence: 'DURDR',
    image: 'ems_mortar_sentry.svg',
    groupId: 'robotics_workshop',
    group: 'Robotics Workshop',
  },
  {
    id: 56,
    name: 'Patriot Exosuit',
    sequence: 'LDRULDD',
    image: 'patriot_exosuit.svg',
    groupId: 'robotics_workshop',
    group: 'robotics_workshop',
  },
]

export default hd2Sequences
